version: "3.7"
services:
  monitoramento:
    image: marcelogbjunior/webhook_proxy:1.0.0
    container_name: webhook_proxy_container
    ports:
      - "3024:3024"
    volumes:
      - ".:/web"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=nerus
      - DB_PASS=nerus
      - DB_NAME=sqlmonitoramento
      - PORT=3024
    restart: always
